// src/App.tsx
import './style.css';
import SideBar from './Sidebar';
import DataViewerDialog, {DialogRef} from './DataViewerDialog';
import { useEffect, useRef } from 'react';
import { chartEventHandler } from './chart-event-handler';
import { Storage } from './stroage';

declare global {
  namespace JSX {
    interface IntrinsicElements {
      [name: string]: React.DetailedHTMLProps<any, HTMLElement>;
    }
  }
}
export default function() {
	const dialogRef = useRef<DialogRef>(null);

  const formflow = Storage.getItem('formflow') || 'Untitled';
  const {selected, chart} = formflow;

  useEffect(() => {
    const chartEl = document.querySelector('.x.formflow') as any;
    const formDesigner = document.querySelector('.x.form-designer') as any;
    formDesigner.editor.on('update', function() {  // html is updated
      const html = formDesigner.html.replace(/^<body>/,'').replace(/<\/body>$/,''); 
      (selected.type === 'custom') && chartEl.updateNodeData(selected.id, {html})
    });

    chartEl.setData(chart);

    document.body.addEventListener('formflow', e => chartEventHandler(e));
    window.addEventListener('resize', _e => {
      (document.querySelector('.x.formflow') as any).getInstance().fitView();
    })

    document.body.addEventListener('resize-move', _e => { // x-resize event handler
      (document.querySelector('.x.formflow') as any).getInstance().fitView();
    })

    document.body.addEventListener('monaco-change', (e:any) => { // monaco editor change handler
      console.log(e.detail);
    });

    document.body.addEventListener('sidebar-message', (event: any) => { // sidebar message handler
      if (event.detail === 'show-data') {
        const chartEl = document.querySelector('.x.formflow') as any;
        dialogRef.current?.show({chartData: chartEl.getData(), chartInstance: chartEl.getInstance()})
      }
    });
  }, []);

  return (<>
    <button 
      className="sidebar toggle position-absolute top-0 start-0 border-0 fs-4" 
      style={{zIndex: 1}}>☰</button>
    <h1 hidden>Form Flow Dashboard</h1>

    <SideBar></SideBar>

    <x-resize className="h-100">
      <div className="position-relative" style={{width: '33%'}}>
        <x-formflow></x-formflow>
      </div>
      <div className="accordion flex-fill" id="right-section" role="navigation">
        <div className="accordion-item">
          <h2 className="accordion-header" id="headingTwo">
            <button className="accordion-button collapsed" data-bs-toggle="collapse" data-bs-target="#form-designer">
              {selected.data?.label} form
            </button>
          </h2>
          <div id="form-designer" className="accordion-collapse collapse" data-bs-parent="#right-section">
            <div className="accordion-body p-0 py-1">
              <x-formdesigner></x-formdesigner>
            </div>
          </div>
        </div>
        <div className="accordion-item">
          <h2 className="accordion-header" id="headingOne">
            <button className="accordion-button collapsed" data-bs-toggle="collapse" data-bs-target="#monaco-editor">
              {selected.data?.label} properties
            </button>
          </h2>
          <div id="monaco-editor" className="accordion-collapse collapse" data-bs-parent="#right-section">
            <div className="accordion-body">
              <x-monaco data-language="json"></x-monaco>
            </div>
          </div>
        </div>
      </div>
    </x-resize>

    <DataViewerDialog ref={dialogRef}/> 
  </>)
}

// dashboard/src/app.svelte
<script lang='ts'>
  import type { FormDesigner, FormDiagram } from '@formflow/elements/src';
  import { onMount } from 'svelte';

  import AppSideBar from './app-sidebar.svelte';
  import AppDataDialog from './app-data.dialog.svelte';
  import AppFileDialog from './app-file.dialog.svelte';
  import currentFile from './store';
  import equal from 'fast-deep-equal';
  import { setForm } from './app';

  // custom elements
  let chartEl: FormDiagram;
  let menuEl: AppSideBar;
  let formDesigner: FormDesigner;
  let appDataDialog: AppDataDialog;
  let appFileDialog: AppFileDialog;

  let formProps = $currentFile.properties || {default: {}};

  onMount(() => {
    $currentFile.setChartEl(chartEl);
    formDesigner.on('update', function() { 
      const html = formDesigner.getHtml().replace(/^<body>/,'').replace(/<\/body>$/,''); 

      // update chart node data
      chartEl.setNodeData(activeNodeId, {html})
      // update storage node data
      const nodes = $currentFile.nodes;
      const nodeIndex = nodes.findIndex(node => node.id == activeNodeId) as number;
      nodes[nodeIndex].html = html;
      $currentFile.nodes = nodes;
    });
  });

  $: activeNodeId = $currentFile.activeNode?.id;
  $: activeNodeName = $currentFile.activeNode?.data?.label || '';

  function formPropsChanged(e: any) {
    $currentFile.properties = JSON.parse(e.detail);
  }

  function handleSideBarMessage(event: any) {
    const {dataMessage, fileMessage} = event.detail;
    fileMessage && appFileDialog.show(fileMessage);
    dataMessage && appDataDialog.show(dataMessage);
  }

  function handleReactflowEvent(e:any) {
    document.querySelectorAll('.collapse.show') // collapse all accordion
      .forEach(el => new (window as any).bootstrap.Collapse(el));
    (document.querySelector('#form-designer-group') as any).style.display =  // if not node, hide designer 
      e.detail.node?.type === 'custom' ? '': 'none';

    const {action, node, edge} = e.detail;
    node && ($currentFile.activeNode = node);
    if (action === 'init') { // when init, select the start node
      const {nodes, edges} = chartEl.getData();
      const node = nodes.find(el => el.id === 'start');
      chartEl.fireEvent({action: 'selected', type: 'node', node, nodes, edges})
    } else if (action === 'selected') { 
      if (node?.type === 'start' || node?.type === 'end' || edge?.type === 'custom') {
        new (window as any).bootstrap.Collapse(document.querySelector('#properties'));
      } 
      else if (node?.type === 'custom') {
        new (window as any).bootstrap.Collapse(document.querySelector('#form-designer'));
        $currentFile.activeNode = node;
        if (!equal($currentFile.chart, chartEl?.getData())) {
          $currentFile.modified = true;
          $currentFile.chart = chartEl?.getData();
        }

        const nodes = chartEl.getData().nodes;
        const nodeIndex = nodes.findIndex(el => el.id == node.id) as number;
        const html = nodes[nodeIndex].data.html;
        setForm(chartEl?.getData(), node, html); // set stepper, html, css
      }
    }
  }
</script>

<style lang="scss"></style>

<svelte:window on:resize={() => chartEl.getInstance().fitView()} />

<button data-x-target="sidebar" class="position-absolute top-0 start-0 border-0 fs-4" style="z-index: 1">☰</button>
<h1 hidden>Form Flow Dashboard</h1> <!--for a11y-->

<AppSideBar bind:this={menuEl} 
  on:message={handleSideBarMessage}
></AppSideBar>

<resize-divs width class="h-100" on:resize-move={() => chartEl.getInstance().fitView()}>
  <div class="position-relative" style="width: 33%">
    <form-diagram bind:this={chartEl} 
      on:reactflow={handleReactflowEvent}>
    </form-diagram>
  </div>
  <div class="accordion flex-fill" id="right-section" role="navigation">
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingOne">
        <button class="accordion-button collapsed" data-bs-toggle="collapse" data-bs-target="#properties">
           {activeNodeName} Properties of "{$currentFile?.name || 'Untitled'}" 
        </button>
      </h2>
      <div id="properties" class="accordion-collapse collapse" data-bs-parent="#right-section">
        <div class="accordion-body">
          <monaco-editor language="json"
            value={JSON.stringify(formProps, null, '  ')}
            on:monaco-change={formPropsChanged}
          ></monaco-editor>
        </div>
      </div>
    </div>
    <div class="accordion-item" id="form-designer-group">
      <h2 class="accordion-header" id="headingTwo">
        <button class="accordion-button collapsed" data-bs-toggle="collapse" data-bs-target="#form-designer">
          Form Designer 
        </button>
      </h2>
      <div id="form-designer" class="accordion-collapse collapse" data-bs-parent="#right-section">
        <div class="accordion-body p-0 py-1">
          <form-designer bind:this={formDesigner}></form-designer>
        </div>
      </div>
    </div>
  </div>
</resize-divs>

<AppDataDialog bind:this={appDataDialog}></AppDataDialog>
<AppFileDialog bind:this={appFileDialog}></AppFileDialog>
