// src/app/App.svelte
<style>
  :global(html, body) { height: 100% }
  #monaco-editor { height: 100%; }
  #monaco-editor x-monaco { height: 100%; }
  .accordion-body { height: 100%; }
</style>

<script lang="ts">
  import { onMount } from 'svelte';

  import SideBar from '../Sidebar.svelte';
  import DataViewerDialog from '../dialogs/data-viewer.dialog.svelte';
  import { name, selected, chart } from '../store/store';
  import { chartEventHandler } from './chart-event-handler';

  onMount(() => {
    const chartEl = document.querySelector('.x.formflow') as any;
    const formDesigner = document.querySelector('.x.form-designer') as any;
    formDesigner.editor.on('update', function() {  // html is updated
      const html = formDesigner.html.replace(/^<body>/,'').replace(/<\/body>$/,''); 
      ($selected.type === 'custom') && chartEl.updateNodeData($selected.id, {html})
    });

    chartEl.setData($chart);
  });

  document.body.addEventListener('formflow', e => chartEventHandler(e));
  
  window.addEventListener('resize', e => {
    (document.querySelector('.x.formflow') as any).getInstance().fitView();
  })

  document.body.addEventListener('resize-move', e => { // x-resize event handler
    (document.querySelector('.x.formflow') as any).getInstance().fitView();
  })

  document.body.addEventListener('monaco-change', (e:any) => { // monaco editor change handler
    console.log(e.detail);
  });

  let dataViewerDialog, openSaveFileDialog;
  document.body.addEventListener('sidebar-message', (event: any) => { // sidebar message handler
    if (event.detail === 'show-data') {
     const chartEl = document.querySelector('.x.formflow') as any;
     dataViewerDialog.show({chartData: chartEl.getData(), chartInstance: chartEl.getInstance()})
    }
  });
</script>

<button class="sidebar toggle position-absolute top-0 start-0 border-0 fs-4" style="z-index: 1">☰</button>
<h1 hidden>Form Flow Dashboard</h1> <!--for a11y-->

<SideBar></SideBar>

<x-resize width class="h-100">
  <div class="position-relative" style="width: 33%">
    <x-formflow></x-formflow>
  </div>
  <div class="accordion flex-fill" id="right-section" role="navigation">
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingTwo">
        <button class="accordion-button collapsed" data-bs-toggle="collapse" data-bs-target="#form-designer">
          {$selected?.data?.label} form
        </button>
      </h2>
      <div id="form-designer" class="accordion-collapse collapse" data-bs-parent="#right-section">
        <div class="accordion-body p-0 py-1">
          <x-formdesigner></x-formdesigner>
        </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingOne">
        <button class="accordion-button collapsed" data-bs-toggle="collapse" data-bs-target="#monaco-editor">
          {$selected?.data?.label} properties
        </button>
      </h2>
      <div id="monaco-editor" class="accordion-collapse collapse" data-bs-parent="#right-section">
        <div class="accordion-body">
          <x-monaco data-language="json"></x-monaco>
        </div>
      </div>
    </div>
  </div>
</x-resize>

<DataViewerDialog bind:this={dataViewerDialog}></DataViewerDialog>

// src/App/App.tsx
import SideBar from '../Sidebar/Sidebar';
import { useEffect, useState } from 'react';
import { Storage } from '../stroage';
import Chart from '../Chart/Chart';
import FormDesigner from '../FormDesigner/FormDesigner';
import MonacoEditor from '../MonacoEditor/MonacoEditor';
import { Accordion } from 'react-bootstrap';

export default function() {
  const [chartSize, setChartSize] = useState(25);
  const [activeAccordion, setActiveAccordion] = useState('FormDesigner');

  const formflow = Storage.getItem('formflow') || 'Untitled';
  const {selected, chart} = formflow;
  useEffect(() => {
    const chartEl = document.querySelector('x-formflow') as any;
    const formDesigner = document.querySelector('form-designer') as any;
    formDesigner?.editor.on('update', function() {  // html is updated
      const html = formDesigner.html.replace(/^<body>/,'').replace(/<\/body>$/,''); 
      (selected.type === 'custom') && chartEl?.updateNodeData(selected.id, {html})
    });

    chartEl?.setData(chart);

    document.body.addEventListener('formflow', (e: any) => {
      const {action, node} = e.detail;
      const nodeType = node?.type;
      if (nodeType) {
        const designRequired = action === 'selected' && ['custom', 'thankyou'].includes(nodeType);
        const activeSection = designRequired ? 'FormDesigner' : 'Properties';
        setActiveAccordion(activeSection);
      }
    });

    window.addEventListener('resize', _e => {
      (document.querySelector('x-formflow') as any).getInstance().fitView();
    })

    document.body.addEventListener('resize-move', _e => { // x-resize event handler
      (document.querySelector('x-formflow') as any).getInstance().fitView();
    })

  }, []);

  function toggleChartSize() { 
    const chartSizes = [0, 25, 50, 75, 100];
    const ndx = chartSizes.indexOf(chartSize);
    setChartSize( chartSizes[ (ndx + 1) % chartSizes.length] )
    const chartEl = document.querySelector('x-formflow') as any;
    setTimeout(() => chartEl.getInstance().fitView(), 100)
  }

  return (
    <div className="container mw-100">
      <SideBar></SideBar>
      <button onClick={toggleChartSize}>Toggle chart size</button>

      <div className="d-flex">
        <Chart id="chart" 
          className='vh-100 position-relative' 
          style={{width: chartSize+'%', display: chartSize ? 'block' : 'none'}}>
        </Chart>
        <Accordion 
          activeKey={activeAccordion}
          style={{width: (100-chartSize)+'%', display: (100-chartSize) ? 'block' : 'none'}}>
          <Accordion.Item eventKey="Properties">
            <Accordion.Header onClick={() => setActiveAccordion('Properties')}>
              {selected?.data?.label} properties
            </Accordion.Header>
            <Accordion.Body>
              <MonacoEditor language="json" value="" />
            </Accordion.Body>
          </Accordion.Item>

          <Accordion.Item eventKey="FormDesigner">
            <Accordion.Header onClick={() => setActiveAccordion('FormDesigner')}>
              {selected?.data?.label} form
            </Accordion.Header>
            <Accordion.Body>
              <FormDesigner />
            </Accordion.Body>
          </Accordion.Item>
        </Accordion>
      </div>
    </div>
  )
}
