// src/app.svelte
<style>
  :global(html, body) { height: 100% }
  #node-edge-data { height: 100%; }
  .accordion-body { height: 100%; }
  #node-edge-data x-monaco { height: 100%; }
</style>

<script lang='ts'>
  import type { FormDesigner, Monaco, Formflow } from 'elements-x';
  import { StepperStorage } from 'elements-x';
  import { onMount } from 'svelte';
  import equal from 'fast-deep-equal';

  import AppSideBar from './app-sidebar.svelte';
  import AppDataDialog from './app-data.dialog.svelte';
  import AppFileDialog from './app-file.dialog.svelte';
  import currentFile from './store';
  // import { setForm } from './app';

  // custom elements
  let chartEl: Formflow;
  let menuEl: AppSideBar;
  let formDesigner: FormDesigner;
  let monacoEditor: Monaco;
  let appDataDialog: AppDataDialog;
  let appFileDialog: AppFileDialog;

  function formPropsChanged(e: any) {
    console.log(e.detail);
  }

  $: selectedId = $currentFile.selected?.id;
  $: selectedType = $currentFile.selected?.source ? 'EDGE' : 'NODE';
  $: selectedLabel = $currentFile.selected?.data?.label || $currentFile.selected?.label || '';

  onMount(() => {
    $currentFile.setChartEl(chartEl);
    formDesigner.on('update', function() {  // html is updated
      const html = formDesigner.getHtml().replace(/^<body>/,'').replace(/<\/body>$/,''); 
      selectedType === 'NODE' && chartEl.updateNodeData(selectedId, {html})
    });
  });

  function handleSideBarMessage(event: any) {
    const {dataMessage, fileMessage} = event.detail;
    fileMessage && appFileDialog.show(fileMessage);
    dataMessage && appDataDialog.show(dataMessage);
  }

  function showTab(id) {
    const nodeEdgeDataSection: any = document.querySelector('.accordion-item:has(#node-edge-data)');
    const formDesignerSection: any = document.querySelector('.accordion-item:has(#form-designer)');
    const bootstrap = (window as any).bootstrap;
    if (id === 'node-edge-data') {
      formDesignerSection.style.display = 'none';
      nodeEdgeDataSection.style.height = '100%';
    } else {
      formDesignerSection.style.display = '';
      nodeEdgeDataSection.style.height = 'auto';
    }
    
    // collapse all bootstrap accordions, then show only selected one
    document.querySelectorAll('.collapse.show').forEach(el => new bootstrap.Collapse(el));
    new bootstrap.Collapse(document.getElementById(id));
  }

  function handleReactflowEvent(e: any) {
    const {action, type, node, edge} = e.detail;
    if (action === 'init') { // when init, select the start node
      (window as any).reactflow = chartEl.getInstance();
      (window as any).reactflow.zoomOut();

      showTab('node-edge-data');
      const {nodes, edges} = chartEl.getData();
      const node = nodes.find(el => el.id === 'start');
      chartEl.fireEvent({action: 'selected', type: 'node', node, nodes, edges})
    } else if (action === 'selected') { 
      $currentFile.selected = node || edge;

      const editorValue = 
        node?.data?.props || edge?.data?.props || {id: node?.id || edge?.id};
      monacoEditor.setValue(JSON.stringify(editorValue, null, '  '));
      if (node?.type === 'start') {
        showTab('node-edge-data');
      } else if (node?.type === 'end') {
        showTab('node-edge-data');
      } else if (edge?.type === 'custom') {
        showTab('node-edge-data');
      } else if (edge?.type === 'custom') {
      } else if (node?.type === 'custom') {
        showTab('form-designer');
        if (!equal($currentFile.chart, chartEl?.getData())) {
          $currentFile.modified = true;
          $currentFile.chart = chartEl?.getData();
        }

        const nodes = chartEl.getData().nodes;
        // const nodeIndex = nodes.findIndex(el => el.id == node.id) as number;
        // const html = nodes[nodeIndex].data.html;
        // setForm(chartEl?.getData(), node, html); // set stepper, html, css
      }
    } else if (action === 'change' && type === 'chart') {
      StepperStorage.setItem('currentFormflow.chart', chartEl.getData());
    }
  }
</script>

<svelte:window on:resize={() => chartEl.getInstance().fitView()} />

<button class="sidebar toggle position-absolute top-0 start-0 border-0 fs-4" style="z-index: 1">☰</button>
<h1 hidden>Form Flow Dashboard</h1> <!--for a11y-->

<AppSideBar bind:this={menuEl} 
  on:message={handleSideBarMessage}
></AppSideBar>

<x-resize width class="h-100" on:resize-move={() => chartEl.getInstance().fitView()}>
  <div class="position-relative" style="width: 33%">
    <x-formflow bind:this={chartEl} on:reactflow={handleReactflowEvent}>
    </x-formflow>
  </div>
  <div class="accordion flex-fill" id="right-section" role="navigation">
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingOne">
        <button class="accordion-button collapsed" data-bs-toggle="collapse" data-bs-target="#node-edge-data">
           Properties of {selectedType.toLowerCase()} "{$currentFile?.name || 'Untitled'}" - "{selectedLabel}"
        </button>
      </h2>
      <div id="node-edge-data" class="accordion-collapse collapse" data-bs-parent="#right-section">
        <div class="accordion-body">
          <x-monaco bind:this={monacoEditor} on:monaco-change={formPropsChanged} data-language="json">
          </x-monaco>
        </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingTwo">
        <button class="accordion-button collapsed" data-bs-toggle="collapse" data-bs-target="#form-designer">
          Form Designer 
        </button>
      </h2>
      <div id="form-designer" class="accordion-collapse collapse" data-bs-parent="#right-section">
        <div class="accordion-body p-0 py-1">
          <x-formdesigner bind:this={formDesigner}></x-formdesigner>
        </div>
      </div>
    </div>
  </div>
</x-resize>

<AppDataDialog bind:this={appDataDialog}></AppDataDialog> 
<AppFileDialog bind:this={appFileDialog}></AppFileDialog>

// src/App.tsx
import './style.css';
import SideBar from './Sidebar';
import DataViewerDialog, {DialogRef} from './DataViewerDialog';
import { useEffect, useRef } from 'react';
import { chartEventHandler } from './chart-event-handler';
import { Storage } from './stroage';

declare global {
  namespace JSX {
    interface IntrinsicElements {
      [name: string]: React.DetailedHTMLProps<any, HTMLElement>;
    }
  }
}
export default function() {
	const dialogRef = useRef<DialogRef>(null);

  const formflow = Storage.getItem('formflow') || 'Untitled';
  const {selected, chart} = formflow;

  useEffect(() => {
    const chartEl = document.querySelector('.x.formflow') as any;
    const formDesigner = document.querySelector('.x.form-designer') as any;
    formDesigner.editor.on('update', function() {  // html is updated
      const html = formDesigner.html.replace(/^<body>/,'').replace(/<\/body>$/,''); 
      (selected.type === 'custom') && chartEl.updateNodeData(selected.id, {html})
    });

    chartEl.setData(chart);

    document.body.addEventListener('formflow', e => chartEventHandler(e));
    window.addEventListener('resize', _e => {
      (document.querySelector('.x.formflow') as any).getInstance().fitView();
    })

    document.body.addEventListener('resize-move', _e => { // x-resize event handler
      (document.querySelector('.x.formflow') as any).getInstance().fitView();
    })

    document.body.addEventListener('monaco-change', (e:any) => { // monaco editor change handler
      console.log(e.detail);
    });

    document.body.addEventListener('sidebar-message', (event: any) => { // sidebar message handler
      if (event.detail === 'show-data') {
        const chartEl = document.querySelector('.x.formflow') as any;
        dialogRef.current?.show({chartData: chartEl.getData(), chartInstance: chartEl.getInstance()})
      }
    });
  }, []);

  return (<>
    <button 
      className="sidebar toggle position-absolute top-0 start-0 border-0 fs-4" 
      style={{zIndex: 1}}>☰</button>
    <h1 hidden>Form Flow Dashboard</h1>

    <SideBar></SideBar>

    <x-resize className="h-100">
      <div className="position-relative" style={{width: '33%'}}>
        <x-formflow></x-formflow>
      </div>
      <div className="accordion flex-fill" id="right-section" role="navigation">
        <div className="accordion-item">
          <h2 className="accordion-header" id="headingTwo">
            <button className="accordion-button collapsed" data-bs-toggle="collapse" data-bs-target="#form-designer">
              {selected.data?.label} form
            </button>
          </h2>
          <div id="form-designer" className="accordion-collapse collapse" data-bs-parent="#right-section">
            <div className="accordion-body p-0 py-1">
              <x-formdesigner></x-formdesigner>
            </div>
          </div>
        </div>
        <div className="accordion-item">
          <h2 className="accordion-header" id="headingOne">
            <button className="accordion-button collapsed" data-bs-toggle="collapse" data-bs-target="#monaco-editor">
              {selected.data?.label} properties
            </button>
          </h2>
          <div id="monaco-editor" className="accordion-collapse collapse" data-bs-parent="#right-section">
            <div className="accordion-body">
              <x-monaco data-language="json"></x-monaco>
            </div>
          </div>
        </div>
      </div>
    </x-resize>

    <DataViewerDialog ref={dialogRef}/> 
  </>)
}
