// src/Sidebar.tsx
declare global {
  namespace JSX {
    interface IntrinsicElements {
      'x-sidebar': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement>;
    }
  }
}

export default function() {

  function showData() {
    document.dispatchEvent(new CustomEvent('sidebar-message', {bubbles: true, detail: 'show-data'}));
  }

  return (
    <x-sidebar>
      <button className="btn btn-light" onClick={showData}>Show data</button>
    </x-sidebar>
  );

}

// src/Sidebar.svelte
<style>
  li:not(:has(ul)) { cursor: pointer; }
  li:not(:has(ul)):hover { background: #EEE;}
</style>

<script lang="typescript">
  let thisEl;
  
  function showData() {
    thisEl.dispatchEvent(new CustomEvent('sidebar-message', {bubbles: true, detail: 'show-data'}));
  }
</script>

<!-- svelte-ignore a11y-click-events-have-key-events a11y-no-noninteractive-element-interactions -->
<x-sidebar bind:this={thisEl}>
  <button class="btn btn-light" on:click={showData}>Show data</button>
</x-sidebar>
